language: ruby
rvm: 2.4.1

branches:
  only:
    - master

notifications:
  email:
    on_success: always
    on_failure : always 

script:
 - gem update --system
 - gem install bundler
 - bundler update --bundler
 - gem install jekyll bundler
 - bundle exec jekyll build

after_success:
  - firebase deploy --token "1//0e1DI6dOJ0jGhCgYIARAAGA4SNwF-L9IrH18xyzH3xCxzcEd_29mJQzaFGQMT9tiLPqqCD5RdJvCqr5S4THdAybsbTPfqlGWqwF8" 

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false
